// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: game_xzdd/game.proto

package game_xzdd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready int32 `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // 准备消息 1 准备  2 取消准备
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{0}
}

func (x *ReadyRequest) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

type ReadyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready  int32 `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // 准备消息 1 准备  2 取消准备
	SiteId int32 `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *ReadyResponse) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

// 开局消息
type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zhuang int32   `protobuf:"varint,1,opt,name=zhuang,proto3" json:"zhuang,omitempty"`
	Sezi   []int32 `protobuf:"varint,2,rep,packed,name=sezi,proto3" json:"sezi,omitempty"`
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{2}
}

func (x *StartGame) GetZhuang() int32 {
	if x != nil {
		return x.Zhuang
	}
	return 0
}

func (x *StartGame) GetSezi() []int32 {
	if x != nil {
		return x.Sezi
	}
	return nil
}

// 发手牌
type FaiPai struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pai []int32 `protobuf:"varint,1,rep,packed,name=pai,proto3" json:"pai,omitempty"`
}

func (x *FaiPai) Reset() {
	*x = FaiPai{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaiPai) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaiPai) ProtoMessage() {}

func (x *FaiPai) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaiPai.ProtoReflect.Descriptor instead.
func (*FaiPai) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{3}
}

func (x *FaiPai) GetPai() []int32 {
	if x != nil {
		return x.Pai
	}
	return nil
}

// 定缺
type DingQueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Que int32 `protobuf:"varint,1,opt,name=que,proto3" json:"que,omitempty"`
}

func (x *DingQueRequest) Reset() {
	*x = DingQueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingQueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingQueRequest) ProtoMessage() {}

func (x *DingQueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingQueRequest.ProtoReflect.Descriptor instead.
func (*DingQueRequest) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{4}
}

func (x *DingQueRequest) GetQue() int32 {
	if x != nil {
		return x.Que
	}
	return 0
}

type DingQueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Que    int32 `protobuf:"varint,1,opt,name=que,proto3" json:"que,omitempty"`
	SiteId int32 `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
}

func (x *DingQueResponse) Reset() {
	*x = DingQueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DingQueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DingQueResponse) ProtoMessage() {}

func (x *DingQueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DingQueResponse.ProtoReflect.Descriptor instead.
func (*DingQueResponse) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{5}
}

func (x *DingQueResponse) GetQue() int32 {
	if x != nil {
		return x.Que
	}
	return 0
}

func (x *DingQueResponse) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

// 摸牌
type PlayerMoPai struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId int32 `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Pai    int32 `protobuf:"varint,2,opt,name=pai,proto3" json:"pai,omitempty"`
}

func (x *PlayerMoPai) Reset() {
	*x = PlayerMoPai{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMoPai) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoPai) ProtoMessage() {}

func (x *PlayerMoPai) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoPai.ProtoReflect.Descriptor instead.
func (*PlayerMoPai) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerMoPai) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *PlayerMoPai) GetPai() int32 {
	if x != nil {
		return x.Pai
	}
	return 0
}

type UserOptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opt int32 `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	Pai int32 `protobuf:"varint,3,opt,name=pai,proto3" json:"pai,omitempty"`
}

func (x *UserOptRequest) Reset() {
	*x = UserOptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOptRequest) ProtoMessage() {}

func (x *UserOptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOptRequest.ProtoReflect.Descriptor instead.
func (*UserOptRequest) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{7}
}

func (x *UserOptRequest) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *UserOptRequest) GetPai() int32 {
	if x != nil {
		return x.Pai
	}
	return 0
}

type UserOptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId int32 `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Opt    int32 `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	Pai    int32 `protobuf:"varint,3,opt,name=pai,proto3" json:"pai,omitempty"`
}

func (x *UserOptResponse) Reset() {
	*x = UserOptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOptResponse) ProtoMessage() {}

func (x *UserOptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOptResponse.ProtoReflect.Descriptor instead.
func (*UserOptResponse) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{8}
}

func (x *UserOptResponse) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UserOptResponse) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *UserOptResponse) GetPai() int32 {
	if x != nil {
		return x.Pai
	}
	return 0
}

// 玩家可以有的操作
type PlayerOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId int32   `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Opt    []int32 `protobuf:"varint,2,rep,packed,name=opt,proto3" json:"opt,omitempty"`
}

func (x *PlayerOpt) Reset() {
	*x = PlayerOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOpt) ProtoMessage() {}

func (x *PlayerOpt) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOpt.ProtoReflect.Descriptor instead.
func (*PlayerOpt) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerOpt) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *PlayerOpt) GetOpt() []int32 {
	if x != nil {
		return x.Opt
	}
	return nil
}

// 结算信息
type UserSettleAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId      int32 `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	IsHu        int32 `protobuf:"varint,2,opt,name=isHu,proto3" json:"isHu,omitempty"`
	IsDianPao   int32 `protobuf:"varint,3,opt,name=isDianPao,proto3" json:"isDianPao,omitempty"`
	HuType      int32 `protobuf:"varint,4,opt,name=huType,proto3" json:"huType,omitempty"`
	DianPaoType int32 `protobuf:"varint,5,opt,name=dianPaoType,proto3" json:"dianPaoType,omitempty"`
	HuPai       int32 `protobuf:"varint,6,opt,name=huPai,proto3" json:"huPai,omitempty"`
	HuFan       int32 `protobuf:"varint,7,opt,name=huFan,proto3" json:"huFan,omitempty"`
	GangFan     int32 `protobuf:"varint,8,opt,name=gangFan,proto3" json:"gangFan,omitempty"`
	Total       int32 `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UserSettleAccount) Reset() {
	*x = UserSettleAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSettleAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettleAccount) ProtoMessage() {}

func (x *UserSettleAccount) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettleAccount.ProtoReflect.Descriptor instead.
func (*UserSettleAccount) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{10}
}

func (x *UserSettleAccount) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UserSettleAccount) GetIsHu() int32 {
	if x != nil {
		return x.IsHu
	}
	return 0
}

func (x *UserSettleAccount) GetIsDianPao() int32 {
	if x != nil {
		return x.IsDianPao
	}
	return 0
}

func (x *UserSettleAccount) GetHuType() int32 {
	if x != nil {
		return x.HuType
	}
	return 0
}

func (x *UserSettleAccount) GetDianPaoType() int32 {
	if x != nil {
		return x.DianPaoType
	}
	return 0
}

func (x *UserSettleAccount) GetHuPai() int32 {
	if x != nil {
		return x.HuPai
	}
	return 0
}

func (x *UserSettleAccount) GetHuFan() int32 {
	if x != nil {
		return x.HuFan
	}
	return 0
}

func (x *UserSettleAccount) GetGangFan() int32 {
	if x != nil {
		return x.GangFan
	}
	return 0
}

func (x *UserSettleAccount) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 游戏结束
type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverType  int32                `protobuf:"varint,1,opt,name=overType,proto3" json:"overType,omitempty"`
	DeskStat  []int32              `protobuf:"varint,2,rep,packed,name=deskStat,proto3" json:"deskStat,omitempty"`
	DeskStake int32                `protobuf:"varint,3,opt,name=deskStake,proto3" json:"deskStake,omitempty"` //桌子底注
	UserTotal []*UserSettleAccount `protobuf:"bytes,4,rep,name=userTotal,proto3" json:"userTotal,omitempty"`
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_xzdd_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_game_xzdd_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_game_xzdd_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameOver) GetOverType() int32 {
	if x != nil {
		return x.OverType
	}
	return 0
}

func (x *GameOver) GetDeskStat() []int32 {
	if x != nil {
		return x.DeskStat
	}
	return nil
}

func (x *GameOver) GetDeskStake() int32 {
	if x != nil {
		return x.DeskStake
	}
	return 0
}

func (x *GameOver) GetUserTotal() []*UserSettleAccount {
	if x != nil {
		return x.UserTotal
	}
	return nil
}

var File_game_xzdd_game_proto protoreflect.FileDescriptor

var file_game_xzdd_game_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x78, 0x7a, 0x64, 0x64, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x78, 0x7a, 0x64,
	0x64, 0x22, 0x24, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x22, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x7a, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x7a, 0x69, 0x22,
	0x1a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x50, 0x61, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x69,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x70, 0x61, 0x69, 0x22, 0x22, 0x0a, 0x0e, 0x44,
	0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x75, 0x65, 0x22,
	0x3b, 0x0a, 0x0f, 0x44, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x71, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x50, 0x61, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x61, 0x69, 0x22, 0x34, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x69,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x61, 0x69, 0x22, 0x4d, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x61, 0x69, 0x22, 0x35, 0x0a, 0x09, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70,
	0x74, 0x22, 0xf3, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x73, 0x48, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x69,
	0x73, 0x48, 0x75, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44, 0x69, 0x61, 0x6e, 0x50, 0x61, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x73, 0x44, 0x69, 0x61, 0x6e, 0x50, 0x61,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x75, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x61,
	0x6e, 0x50, 0x61, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x64, 0x69, 0x61, 0x6e, 0x50, 0x61, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x68,
	0x75, 0x50, 0x61, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x75, 0x50, 0x61,
	0x69, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x75, 0x46, 0x61, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x68, 0x75, 0x46, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x6e, 0x67, 0x46,
	0x61, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x61, 0x6e, 0x67, 0x46, 0x61,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x65, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x64, 0x65, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x78, 0x7a, 0x64, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x78, 0x7a, 0x64, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_xzdd_game_proto_rawDescOnce sync.Once
	file_game_xzdd_game_proto_rawDescData = file_game_xzdd_game_proto_rawDesc
)

func file_game_xzdd_game_proto_rawDescGZIP() []byte {
	file_game_xzdd_game_proto_rawDescOnce.Do(func() {
		file_game_xzdd_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_xzdd_game_proto_rawDescData)
	})
	return file_game_xzdd_game_proto_rawDescData
}

var file_game_xzdd_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_game_xzdd_game_proto_goTypes = []interface{}{
	(*ReadyRequest)(nil),      // 0: game_xzdd.ReadyRequest
	(*ReadyResponse)(nil),     // 1: game_xzdd.ReadyResponse
	(*StartGame)(nil),         // 2: game_xzdd.StartGame
	(*FaiPai)(nil),            // 3: game_xzdd.FaiPai
	(*DingQueRequest)(nil),    // 4: game_xzdd.DingQueRequest
	(*DingQueResponse)(nil),   // 5: game_xzdd.DingQueResponse
	(*PlayerMoPai)(nil),       // 6: game_xzdd.PlayerMoPai
	(*UserOptRequest)(nil),    // 7: game_xzdd.UserOptRequest
	(*UserOptResponse)(nil),   // 8: game_xzdd.UserOptResponse
	(*PlayerOpt)(nil),         // 9: game_xzdd.PlayerOpt
	(*UserSettleAccount)(nil), // 10: game_xzdd.UserSettleAccount
	(*GameOver)(nil),          // 11: game_xzdd.GameOver
}
var file_game_xzdd_game_proto_depIdxs = []int32{
	10, // 0: game_xzdd.GameOver.userTotal:type_name -> game_xzdd.UserSettleAccount
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_game_xzdd_game_proto_init() }
func file_game_xzdd_game_proto_init() {
	if File_game_xzdd_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_xzdd_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaiPai); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingQueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DingQueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMoPai); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSettleAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_xzdd_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_xzdd_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_xzdd_game_proto_goTypes,
		DependencyIndexes: file_game_xzdd_game_proto_depIdxs,
		MessageInfos:      file_game_xzdd_game_proto_msgTypes,
	}.Build()
	File_game_xzdd_game_proto = out.File
	file_game_xzdd_game_proto_rawDesc = nil
	file_game_xzdd_game_proto_goTypes = nil
	file_game_xzdd_game_proto_depIdxs = nil
}
